=== kbzonbak/JoannaW/b2blink/irsb2blinkexternalretail/irsb2blinkexternalretailmappings/xsd/OC_Customer.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bbr.cl/OC_Customer" elementFormDefault="qualified" xmlns:oc="http://www.bbr.cl/OC_Customer">
	<!-- Versión Customee Service 1.0 -->
	<element name="order">  
		<complexType>
			<sequence>
				<element name="buyer" type="string"/>
				<element name="vendor" type="string"/>
				<element name="number" type="string"/>
				<element name="ordertype" type="string"/>
				<element name="ordertypename" type="string" minOccurs="0" />
				<element name="previousordertype" type="string"/>
				<element name="complete" type="boolean"/>
				<element name="ticket" type="string" minOccurs="0" />
				<element name="receiptnumber" type="string" minOccurs="0" /> <!-- NRO BOLETA -->
				<element name="status" type="string" minOccurs="0" />
				<element name="numref1" type="string" minOccurs="0" />
				<element name="numref2" type="string" minOccurs="0" />
				<element name="request" type="string" minOccurs="0" />
				<element name="issuedate" type="date" minOccurs="0" />
				<!-- EMISIÓN -->
				<element name="effectivdate" type="date" minOccurs="0" />
				<!-- VIGENCIA -->
				<element name="expirationdate" type="date" minOccurs="0" />
				<!-- VENCIMIENTO -->
				<element name="commitmentdate" type="date" minOccurs="0" />
				<!-- COMPROMISO -->
				<element name="paymentcondition" type="string" minOccurs="0" />
				<element name="observation" type="string" minOccurs="0" />
				<element name="responsible" type="string" minOccurs="0" />
				<element name="responsibleemail" type="string" minOccurs="0" />
				<element name="valid" type="string" minOccurs="0" />
				<element name="deliveryplace" type="oc:local" minOccurs="0"/>
				<element name="saleplace" type="oc:local" minOccurs="0"/>
				<element name="section" minOccurs="0">
					<complexType>
						<sequence>
							<element name="code" type="string" />
							<element name="name" type="string" minOccurs="0" />
						</sequence>
					</complexType>
				</element>
				<element name="client" minOccurs="0">
					<complexType>
						<sequence>
							<element name="name" type="string" />
							<element name="identity" type="string" />
							<element name="checkdigit" type="string" />
							<element name="phone" type="string" minOccurs="0"/>
							<element name="phone2" type="string" minOccurs="0"/>
							<element name="address" type="string" minOccurs="0"/>
							<element name="streetnumber" type="string" minOccurs="0"/>
							<element name="departmetnumber" type="string" minOccurs="0"/>
							<element name="housenumber" type="string" minOccurs="0"/>
							<element name="region" type="string" minOccurs="0"/>
							<element name="commune" type="string" minOccurs="0"/>
							<element name="city" type="string" minOccurs="0"/>
							<element name="location" type="string" minOccurs="0"/>
							<element name="observation" type="string" minOccurs="0"/>
						</sequence>
					</complexType>
				</element>
				<element name="discounts">
					<complexType>
						<sequence minOccurs="0" maxOccurs="unbounded">
							<element name="discounts" type="oc:discount_charge" />
						</sequence>
					</complexType>
				</element>
				<element name="charges">
					<complexType>
						<sequence minOccurs="0" maxOccurs="unbounded">
							<element name="charges" type="oc:discount_charge" />
						</sequence>
					</complexType>
				</element>
				<element name="details">
					<complexType>
						<sequence maxOccurs="unbounded">
							<element name="detail">
								<complexType>
									<sequence>
										<element name="position" type="int" />
										<element name="skubuyer" type="string" />
										<element name="skuvendor" type="string" minOccurs="0" />
										<element name="ean13" type="string" minOccurs="0" />
										<element name="ean13buyer" type="string" minOccurs="0" />
										<element name="productdescription" type="string" minOccurs="0" />
										<element name="codeumc" type="string" minOccurs="0" />
										<!-- UNIDAD MEDIDA DE COMPRA (CAJA  sixpack de bebidas) -->
										<element name="descriptionumc" type="string" minOccurs="0" />
										<!-- DESCRIPCIÓN UNIDAD MEDICA DE COMPRA -->
										<element name="codeumb" type="string" minOccurs="0" />
										<!-- UNIDAD MEDIDA BASE (LATA) -->
										<element name="descriptionumb" type="string" minOccurs="0" />
										<!-- DESCRIPCIÓN UNIDAD MEDICA BASE -->
										<element name="umb_x_umc" type="int" minOccurs="0" />
										<!-- BASE POR COMPRA UNIDADES EN UNA CAJA (6) -->
										<element name="quantityumc" type="int" minOccurs="0" />
										<!-- CANTIDAD UMC -->
										<element name="innerpack" type="int" minOccurs="0" />
										<element name="listcost" type="double" minOccurs="0" />
										<element name="finalcost" type="double" minOccurs="0" />
										<element name="listprice" type="double" minOccurs="0" />
										<element name="item" type="string" minOccurs="0" />
										<!-- RUBRO -->
										<element name="ean1" type="string" minOccurs="0" />            
										<element name="ean2" type="string" minOccurs="0" />            
										<element name="ean3" type="string" minOccurs="0" />            
										<element name="stylecode" type="string" minOccurs="0" />       
										<element name="styledescription" type="string" minOccurs="0" />
										<element name="stylebrand" type="string" minOccurs="0" />
										<element name="numref1" type="string" minOccurs="0" />
										<element name="numref2" type="string" minOccurs="0" />
										<element name="tolerance" type="string" minOccurs="0" />
										<element name="productdeliverydate" type="date" minOccurs="0" />
										<element name="observation" type="string" minOccurs="0"/>
										<element name="freightcost" type="double" minOccurs="0" />
										<!-- COSTO FLETE -->
										<element name="freightweight" type="double" minOccurs="0" />
										<!-- PESO FLETE -->
										<element name="discounts">
											<complexType>
												<sequence minOccurs="0" maxOccurs="unbounded">
													<element name="discount" type="oc:discount_charge" />
												</sequence>
											</complexType>
										</element>
										<element name="charges">
											<complexType>
												<sequence minOccurs="0" maxOccurs="unbounded">
													<element name="charge" type="oc:discount_charge" />
												</sequence>
											</complexType>
										</element>
										<element name="predistributions">
											<complexType>
												<sequence minOccurs="0" maxOccurs="unbounded">
													<element name="predistribution">
														<complexType>
															<sequence>
																<element name="deliveryplace" type="oc:local" minOccurs="0"/>
																<element name="quantity" type="int" />
															</sequence>
														</complexType>
													</element>
												</sequence>
											</complexType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

			</sequence>
		</complexType>
	</element>
	<complexType name="discount_charge">
		<sequence>
			<element name="code" type="string" />
			<element name="description" type="string" />
			<element name="procentaje" type="boolean" />
			<element name="value" type="double" />
		</sequence>
	</complexType>
	<complexType name="local">
		<sequence>
			<element name="code" type="string" />
			<element name="name" type="string" />
		</sequence>
	</complexType>
</schema>

=== kbzonbak/JoannaW/b2blink/b2blinkinterfacesb2b/B2BLinkInterfacesB2B/src/main/resources/bbr/b2b/b2blink/xsd/OC_Customer1.xml
<?xml version="1.0" encoding="UTF-8"?>
<order xmlns="http://www.bbr.cl/OC_Customer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bbr.cl/OC_Customer OC_Customer.xsd ">
	<buyer>buyer</buyer>
	<vendor>vendor</vendor>
	<number>number</number>
	<ordertype>ordertype</ordertype>
	<ordertypename>ordertypename</ordertypename>
	<previousordertype>previousordertype</previousordertype>
	<complete>true</complete>
	<ticket>ticket</ticket>
	<receiptnumber>receiptnumber</receiptnumber>
	<status>status</status>
	<numref1>numref1</numref1>
	<numref2>numref2</numref2>
	<numref3>numref3</numref3>
	<request>request</request>
	<issuedate>2001-01-01</issuedate>
	<effectivdate>2001-01-01</effectivdate>
	<expirationdate>2001-01-01</expirationdate>
	<commitmentdate>2001-01-01</commitmentdate>
	<paymentcondition>paymentcondition</paymentcondition>
	<observation>observation</observation>
	<responsible>responsible</responsible>
	<responsibleemail>responsibleemail</responsibleemail>
	<currency>CLP</currency>
	<valid>valid</valid>
	<deliveryplace>
		<code>code1</code>
		<name>CD 1</name>
	</deliveryplace>
	<saleplace>
		<code>code2</code>
		<name>ONLINE</name>
	</saleplace>
	<section>
		<code>LB</code>
		<name>LÃ­nea blanca</name>
	</section>
	<action>
		<code>ADD</code>
		<description>AGREGAR</description>
	</action>
	<client>
		<name>name</name>
		<identity>identity</identity>
		<checkdigit>checkdigit</checkdigit>
		<phone>phone</phone>
		<phone2>phone2</phone2>
		<address>address</address>
		<streetnumber>streetnumber</streetnumber>
		<apartment>apartment</apartment>
		<housenumber>housenumber</housenumber>
		<region>region</region>
		<commune>commune</commune>
		<city>city</city>
		<location>location</location>
		<observation>observation</observation>
	</client>
	<discounts>
		<discounts>
			<code>code1</code>
			<description>description1</description>
			<percentage>true</percentage>
			<value>0.0</value>
		</discounts>
		<discounts>
			<code>code2</code>
			<description>description2</description>
			<percentage>true</percentage>
			<value>0.0</value>
		</discounts>
	</discounts>
	<charges>
		<charges>
			<code>code1</code>
			<description>description1</description>
			<percentage>true</percentage>
			<value>0.0</value>
		</charges>
		<charges>
			<code>code2</code>
			<description>description2</description>
			<percentage>true</percentage>
			<value>0.0</value>
		</charges>
	</charges>
	<details>
		<detail>
			<position>1</position>
			<skubuyer>LS65SXN</skubuyer>
			<skuvendor>LS65SXN</skuvendor>
			<ean13>3123123123</ean13>
			<ean13buyer>3123123123</ean13buyer>
			<productdescription>Refrigerador InstaView Door-in-Door</productdescription>
			<codeumc>caja</codeumc>
			<descriptionumc></descriptionumc>
			<codeumb>6</codeumb>
			<descriptionumb></descriptionumb>
			<umb_x_umc>12</umb_x_umc>
			<quantityumc>2</quantityumc>
			<innerpack>1</innerpack>
			<listcost>100.0</listcost>
			<finalcost>102.0</finalcost>
			<costaftertaxes>102.0</costaftertaxes>
			<listprice>99.0</listprice>
			<item></item>
			<ean1></ean1>
			<ean2></ean2>
			<ean3></ean3>
			<stylecode></stylecode>
			<styledescription></styledescription>
			<stylebrand></stylebrand>
			<numref1></numref1>
			<numref2></numref2>
			<tolerance></tolerance>
			<productdeliverydate>2001-01-01</productdeliverydate>
			<observation></observation>
			<freightcost>0.0</freightcost>
			<freightweight>0.0</freightweight>
			<discounts>
				<discount>
					<code></code>
					<description></description>
					<percentage>true</percentage>
					<value>1.0</value>
				</discount>
			</discounts>
			<charges>
				<charge>
					<code></code>
					<description></description>
					<percentage>true</percentage>
					<value>10.0</value>
				</charge>
			</charges>
			<predistributions>
				<predistribution>
					<deliveryplace>
						<code>code</code>
						<name>name</name>
					</deliveryplace>
					<quantity>1</quantity>
					<shipping_quantity></shipping_quantity>
					<received_quantity></received_quantity>
					<pending_quantity></pending_quantity>
				</predistribution>
			</predistributions>

		</detail>
	</details>
</order>
