=== kbzonbak/JoannaW/virtuales/falabella ear/FalabellaModuleEAR.ear/properties/OC_consolidado_1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bbr.cl/bbr/OCConsolidado" elementFormDefault="qualified"
  xmlns:occ="http://www.bbr.cl/bbr/OCConsolidado">
	<element name="consolidado">
    	<complexType>
      		<sequence>      			
      			<element name="numeroconsolidado" type="string" />
		        <element name="nombreportal" type="string" />
		        <element name="ticket" type="string" minOccurs="0"/>   

		        <element name="shipto" type="string" />      
		        <element name="edi_data"> 
	         	<complexType>
            		<sequence>
		              <element name="senderIdentification" type="string" />
		              <element name="recipientIdentification" type="string" />              
		              <element name="buyerLocationCode" type="string" />
            		</sequence>
        </complexType>
	</element>
	
    <element name="comprador">
        <complexType>
            <sequence>
	            <element name="rut" type="string" />
	            <element name="razon_social" type="string" />
	            <element name="unidad_negocio" type="string" />
            </sequence>
        </complexType>
    </element>
    
    <element name="vendedor">
        <complexType>
        	<sequence>
	            <element name="rut" type="string" />
	            <element name="razon_social" type="string" />
	            <element name="contacto" type="string" />
	            <element name="direccion" type="string" />
	            <element name="telefono" type="string" />
            </sequence>
     	</complexType>
    </element>
    
    <element name="clientes" >
      	<complexType> 
	      	<sequence minOccurs="0" maxOccurs="unbounded">
			    <element name="cliente" minOccurs="0">
			     	<complexType>
			        	<sequence>
				            <element name="id" type="string" />
				            <element name="nombre" type="string" />				            
				            <element name="rut" type="string" />
				            <element name="telefono" type="string" />
				            <element name="direccion" type="string" />
				            <element name="numcalle" type="string" />
				            <element name="numdepto" type="string" />
				            <element name="numcasa" type="string" />
				            <element name="region" type="string" />
				            <element name="comuna" type="string" />
				            <element name="ciudad" type="string" />
				            <element name="comentario" type="string" />
			            </sequence>
			         </complexType>
			    </element>    
			</sequence>  
    	</complexType>
  	</element>
  	
    <element name="locales">
      	<complexType>
        	<sequence minOccurs="1" maxOccurs="unbounded">
            	<element name="local">
              		<complexType>
              			<sequence>
				            <element name="cod" type="string" />
				            <element name="nombre" type="string" />
				            <element name="direccion" type="string" />
				            <element name="ean" type="string" minOccurs="0" />
				         </sequence>
                	</complexType>
              	</element>
          	</sequence>
       	</complexType>
  	</element>
                
    <element name="detalles">
    	<complexType>
        	<sequence maxOccurs="unbounded">
            	<element name="detalle">
                	<complexType>
                  		<sequence>
						
							<element name="id" type="int"/>
						
		                    <element name="item" type="int"/>
		                    <element name="tipo_oc" type="string"/>
		                    <element name="num_oc" type="string"/>
		                    <element name="f12" type="string" minOccurs="0"/>
		                    <element name="cod_prod_comp" type="string"/>		                    
		                    <element name="seccion" type="string" minOccurs="0"/>
							<element name="cod_seccion" type="string" minOccurs="0"/>
							<element name="nro_boleta" type="string" minOccurs="0"/>
														
							<element name="id_cliente" type="string" minOccurs="0"/>							
		                    <element name="cod_prod_vendedor" type="string" />
		                    <element name="prod_empaque" type="float" />
		                    <element name="cantidad_empaque" type="int" />
		                    <element name="fecha_emision" type="date" />
		        			<element name="fecha_vigencia" type="date" />
							 
							<element name="fecha_compromiso" type="date"  />
							
		        			<element name="fecha_vto" type="date" />
		                    <element name="forma_pago" type="string" minOccurs="0"/>
		                    <element name="responsable" type="string" />
		                    <element name="desc_producto">
                  				<complexType>
	                        		<sequence minOccurs="0" maxOccurs="unbounded">
	                          			<element name="descuento" type="occ:cargo_descuento" />
	                        		</sequence>
                      			</complexType>
               				</element>         		
                 	 		<element name="cargos_prod">
		                        <complexType>
		                        	<sequence minOccurs="0" maxOccurs="unbounded">
		                          		<element name="cargo" type="occ:cargo_descuento" />
		                        	</sequence>
		                      	</complexType>
                    		</element>
                  		</sequence>
                	</complexType>
              	</element>
            </sequence>
    	</complexType>
	</element>
    <element name="predistribuciones">
    	<complexType>
        	<sequence minOccurs="0" maxOccurs="unbounded">
            	<element name="predistribucion">
                	<complexType>
                  		<sequence>
		                    <element name="cod_local" type="string" />							
							<element name="id_detalle" type="string" />							
		                    <element name="sku" type="string" />
		                    <element name="cantidad" type="string" />
                  		</sequence>
                	</complexType>
              	</element>
            </sequence>
  		</complexType>
 	</element>
	
	 <element name="sub-detalles">
    	<complexType>
        	<sequence minOccurs="0" maxOccurs="unbounded">
            	<element name="sub-detalle">
                	<complexType>
                  		<sequence>
							<element name="id_detalle" type="string" />
		                    <element name="SKU" type="string" />
							<element name="dv_codigo_etiq" type="string" />
							<element name="codigo_etiq" type="string" />
							<element name="costo_lista" type="string" />
							<element name="cant_sol" type="string" />
							<element name="cant_des" type="string" minOccurs="0"/>
		                    <element name="costo_final" type="string" />
		                    <element name="ean13" type="string" />							
                  		</sequence>
                	</complexType>
              	</element>
            </sequence>
  		</complexType>
 	</element>
	
	</sequence>
  </complexType>
</element>


  <complexType name="cargo_descuento">
    <sequence>
      <element name="monto" type="float" />
      <element name="porcentaje" type="float" />
      <element name="tipo" type="occ:tipo_cargo_descuento" />
      <element name="glosa" type="string" minOccurs="0" />
      <element name="codigo" type="string" />
    </sequence>
  </complexType>

  <simpleType name="tipo_cargo_descuento">
    <restriction base="string">
      <enumeration value="monto"></enumeration>
      <enumeration value="porcentaje"></enumeration>
    </restriction>
  </simpleType>
</schema>

=== kbzonbak/JoannaW/virtuales/falabella ear/FalabellaModuleEAR.ear/properties/OC_consolidado_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<consolidado xmlns="http://www.bbr.cl/bbr/OCConsolidado" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bbr.cl/bbr/OCConsolidado OC_consolidado_1.0.xsd ">
  <numeroconsolidado>20190218164443440</numeroconsolidado>
    <nombreportal>FALABELLA LOGISTICA</nombreportal>
    <ticket></ticket>
    <shipto>SHIP0078-S</shipto>
    <edi_data>
        <senderIdentification>test</senderIdentification>
        <recipientIdentification>760146102</recipientIdentification>
        <buyerLocationCode></buyerLocationCode>
    </edi_data>
    <comprador>
        <rut>77261280</rut>
        <razon_social>falabella</razon_social>
        <unidad_negocio></unidad_negocio>
    </comprador>
    <vendedor>
        <rut>760146102</rut>
        <razon_social>LG ELECTRONICS INC CHILE LTDA</razon_social>
        <contacto></contacto>
        <direccion></direccion>
        <telefono></telefono>
    </vendedor>
    <clientes>
        <cliente>
        	<id>1</id>
            <nombre>JOSE ALVARO CARO JAUREGUI</nombre>
            <rut></rut>
            <telefono>800388388 opcion 01</telefono>
            <direccion>sector Bellavista frente a planta vinos Aresti s/n Casa Patronal, RIO CLARO</direccion>
            <numcalle>sector Bellavista frente a planta vinos Aresti s/n Casa Patronal</numcalle>
            <numdepto></numdepto>
            <numcasa>(CT HUB-CROSS DOCK ) FALABELLA RETAIL S.A.</numcasa>
            <region></region>
            <comuna>RIO CLARO</comuna>
            <ciudad>RIO CLARO(7REG)</ciudad>
            <comentario>8 900  - 2100 - Orden:5228711646 - HC:12:45 -</comentario>
        </cliente>
    </clientes>
    <locales>
        <local>
            <cod>1057311131</cod>
            <nombre>(CT HUB-CROSS DOCK ) FALABELLA RETAIL S.A.</nombre>
            <direccion></direccion>
            <ean>4024e5faf1e6739ed210e90a3f05499b</ean>
        </local>
    </locales>
    <detalles>
        <detalle>
            <id>48521</id>
            <item>1</item>
            <tipo_oc></tipo_oc>
            <num_oc>685</num_oc>
            <f12>12779869825</f12>
            <cod_prod_comp>6623166</cod_prod_comp>
            <id_cliente>9908</id_cliente>
            <cod_prod_vendedor></cod_prod_vendedor>
            <prod_empaque>1.0</prod_empaque>
            <cantidad_empaque>1</cantidad_empaque>
            <fecha_emision>2019-02-11-03:00</fecha_emision>
            <fecha_vigencia>2019-02-11-03:00</fecha_vigencia>
            <fecha_compromiso>2019-02-11-03:00</fecha_compromiso>
            <fecha_vto>2019-02-12-03:00</fecha_vto>
            <forma_pago>60</forma_pago>
            <responsable></responsable>
            <desc_producto>
                <descuento>
                    <monto>0.0</monto>
                    <porcentaje>0.0</porcentaje>
                    <tipo>monto</tipo>
                    <glosa></glosa>
                    <codigo></codigo>
                </descuento>
            </desc_producto>
            <cargos_prod>
                <cargo>
                    <monto>0.0</monto>
                    <porcentaje>0.0</porcentaje>
                    <tipo>monto</tipo>
                    <glosa></glosa>
                    <codigo></codigo>
                </cargo>
            </cargos_prod>
        </detalle>
    </detalles>
    <predistribuciones></predistribuciones>
    <sub-detalles></sub-detalles>
</consolidado>
